
package br.edu.ifsp.pep.client.servico;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.0
 * Generated source version: 3.0
 * 
 */
@WebService(name = "CertidaoNascimento", targetNamespace = "http://servico.server.pep.ifsp.edu.br/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface CertidaoNascimento {


    /**
     * 
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://servico.server.pep.ifsp.edu.br/CertidaoNascimento/calcularIdadeRequest", output = "http://servico.server.pep.ifsp.edu.br/CertidaoNascimento/calcularIdadeResponse")
    public int calcularIdade(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://servico.server.pep.ifsp.edu.br/CertidaoNascimento/diaSemanaRequest", output = "http://servico.server.pep.ifsp.edu.br/CertidaoNascimento/diaSemanaResponse")
    public String diaSemana(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

}
