
package br.edu.ifsp.pep.client.servico;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.0
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "CertidaoNascimentoImpService", targetNamespace = "http://servico.server.pep.ifsp.edu.br/", wsdlLocation = "http://localhost:8085/servico/certidao?wsdl")
public class CertidaoNascimentoImpService
    extends Service
{

    private final static URL CERTIDAONASCIMENTOIMPSERVICE_WSDL_LOCATION;
    private final static WebServiceException CERTIDAONASCIMENTOIMPSERVICE_EXCEPTION;
    private final static QName CERTIDAONASCIMENTOIMPSERVICE_QNAME = new QName("http://servico.server.pep.ifsp.edu.br/", "CertidaoNascimentoImpService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8085/servico/certidao?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CERTIDAONASCIMENTOIMPSERVICE_WSDL_LOCATION = url;
        CERTIDAONASCIMENTOIMPSERVICE_EXCEPTION = e;
    }

    public CertidaoNascimentoImpService() {
        super(__getWsdlLocation(), CERTIDAONASCIMENTOIMPSERVICE_QNAME);
    }

    public CertidaoNascimentoImpService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CERTIDAONASCIMENTOIMPSERVICE_QNAME, features);
    }

    public CertidaoNascimentoImpService(URL wsdlLocation) {
        super(wsdlLocation, CERTIDAONASCIMENTOIMPSERVICE_QNAME);
    }

    public CertidaoNascimentoImpService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CERTIDAONASCIMENTOIMPSERVICE_QNAME, features);
    }

    public CertidaoNascimentoImpService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CertidaoNascimentoImpService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CertidaoNascimento
     */
    @WebEndpoint(name = "CertidaoNascimentoImpPort")
    public CertidaoNascimento getCertidaoNascimentoImpPort() {
        return super.getPort(new QName("http://servico.server.pep.ifsp.edu.br/", "CertidaoNascimentoImpPort"), CertidaoNascimento.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CertidaoNascimento
     */
    @WebEndpoint(name = "CertidaoNascimentoImpPort")
    public CertidaoNascimento getCertidaoNascimentoImpPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://servico.server.pep.ifsp.edu.br/", "CertidaoNascimentoImpPort"), CertidaoNascimento.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CERTIDAONASCIMENTOIMPSERVICE_EXCEPTION!= null) {
            throw CERTIDAONASCIMENTOIMPSERVICE_EXCEPTION;
        }
        return CERTIDAONASCIMENTOIMPSERVICE_WSDL_LOCATION;
    }

}
